#pragma once
#include "pch.h"
#include <vector>
#include <deque>
#include <atomic>
#include <string>
#include <mutex>
#include <thread>
#include <optional>
#include "MemoryArena.h"
#include "ImageLoader.h"
#include "EditState.h"

// Events generated by the Engine
enum class EventType {
    None,
    ThumbReady,     // Scout Lane Result
    FullReady,      // Heavy Lane Result (Final)
    LoadError,      // Something went wrong
    StatusChange    // For UI debug/status bar "Loading...", "Idle"
};

struct EngineEvent {
    EventType type = EventType::None;
    std::wstring filePath; // Which file is this event for?
    uint64_t navToken = 0; // [Phase 3] Navigation session token for event filtering
    
    // Payload (Optional parts)
    CImageLoader::ThumbData thumbData;     // For ThumbReady
    ComPtr<IWICBitmapSource> fullImage;    // For FullReady
    CImageLoader::ImageMetadata metadata;  // Pre-read metadata (avoids UI blocking)
    std::wstring loaderName;               // Which decoder was used
    
    // [Phase 7] Truth Stage
    bool isScaled = false; // true = Fit Stage (scaled), false = Truth Stage (full res)
};

class ImageEngine {
public:
    ImageEngine(CImageLoader* loader);
    ~ImageEngine();

    // The Main Input: "User wants to go here"
    // fileSize: Used for Threshold Dispatch (Scout/Heavy/Express)
    /// <summary>
    /// Update Runtime Configuration (for Verification Flags)
    /// </summary>
    void UpdateConfig(const RuntimeConfig& cfg);

    /// <summary>
    /// Navigate to a new image
    /// </summary>
    // fileSize: Used for Threshold Dispatch (Scout/Heavy/Express)
    // navToken: [Phase 3] Navigation session token for event filtering
    void NavigateTo(const std::wstring& path, uintmax_t fileSize = 0, uint64_t navToken = 0);
    void SetWindow(HWND hwnd);
    
    // [v3.1] Cancel Heavy Lane when Fast Pass succeeds
    void CancelHeavy() { m_heavy.SetTarget(L""); }

    // The Main Output: Poll this every frame (or via timer)
    // Yields events as they happen.
    // This replaces callbacks.
    // NOTE: C++23 std::generator
    // Ensure you have /std:c++latest or /std:c++20 + VS 17.9+
    // Returns a batch of events
    std::vector<EngineEvent> PollState();

    // Stats
    bool IsIdle() const;
    
    // [Phase 6] Dynamic Gating
    // High Priority = Warp Mode (Skip Slow Decodes)
    void SetHighPriorityMode(bool enabled);
    
    // === Debug/Instrumentation API ===
    enum class HeavyState { IDLE, DECODING, CANCELLING };
    
    struct DebugStats {
        int scoutQueueSize = 0;
        int scoutResultsSize = 0;
        HeavyState heavyState = HeavyState::IDLE;
        size_t memoryUsed = 0;
        size_t memoryTotal = 0;
        int cancelCount = 0;       // Total Heavy cancellations (Regicide)
        int scoutSkipCount = 0;    // Scout skip-middle count
        double scoutLoadTimeMs = 0.0; // Last Scout Load Time
        double heavyDecodeTimeMs = 0.0; // Last Heavy Decode Time

        std::wstring loaderName;   // Last used decoder name
        int heavyPendingCount = 0; // New: Heavy Lane Pending Count
    };
    
    DebugStats GetDebugStats() const;
    void ResetDebugCounters();

private:
    CImageLoader* m_loader;
    RuntimeConfig m_config; // Verification Flags
    QuantumArenaPool m_pool;
    HWND m_hwnd = nullptr;
    std::atomic<bool> m_isHighPriority = false; // Default: Static Mode (Allow everything)

    void QueueEvent(EngineEvent&& e);
    
    // Smart skip for fast formats (PNG/GIF/BMP < 16MP)
    bool ShouldSkipScoutForFastFormat(const std::wstring& path);

    // --- Lane 1: The Scout ---
    class ScoutLane {
    public:
        ScoutLane(ImageEngine* parent, CImageLoader* loader);
        ~ScoutLane();

        void Push(const std::wstring& path);
        std::optional<EngineEvent> TryPopResult();
        bool IsQueueEmpty() const;
        
        // Debug
        int GetQueueSize() const;
        int GetResultsSize() const;
        int GetSkipCount() const { return m_skipCount.load(); }
        void ResetSkipCount() { m_skipCount = 0; }
        
        // [v3.2] Scout Loader Name (for HUD)
        std::wstring GetLastLoaderName() const {
            std::lock_guard lock(m_debugMutex);
            return m_lastLoaderName;
        }
        
        std::atomic<double> m_lastLoadTimeMs{ 0.0 }; // Public atomic for easy access

    private:
        void QueueWorker(); // The Scout Thread Function

        CImageLoader* m_loader;
        ImageEngine* m_parent;
        
        std::jthread m_thread; 
        mutable std::mutex m_queueMutex;
        mutable std::mutex m_debugMutex; // [v3.2] For loader name
        std::deque<std::wstring> m_queue; 
        std::deque<EngineEvent> m_results; 
        std::atomic<bool> m_stopSignal = false;
        std::condition_variable m_cv;
        std::atomic<int> m_skipCount = 0;
        std::wstring m_lastLoaderName; // [v3.2] Scout Loader Record
    } m_scout;

    // --- Lane 2: The Heavy Lifter ---
    class HeavyLane {
    public:
        HeavyLane(ImageEngine* parent, CImageLoader* loader, QuantumArenaPool* pool);
        ~HeavyLane();

        void SetTarget(const std::wstring& path); // The Single Slot
        std::optional<EngineEvent> TryPopResult();
        bool IsBusy() const { return m_isBusy; }
        bool IsCancelling() const { return m_isCancelling; }
        int GetCancelCount() const { return m_cancelCount.load(); }
        void ResetCancelCount() { m_cancelCount = 0; }
        
        HeavyState GetState() const {
            if (m_isCancelling) return HeavyState::CANCELLING;
            if (m_isBusy) return HeavyState::DECODING;
            return HeavyState::IDLE;
        }

        // Debug Access (Called by parent)
        double GetLastDecodeTime() const { return m_lastDecodeTimeMs.load(); }
        std::wstring GetLastLoaderName() const { 
            std::lock_guard lock(m_debugMutex);
            return m_lastLoaderName; 
        }
        
        int GetPendingCount() {
            std::lock_guard lock(m_jobMutex);
            return m_hasPendingJob ? 1 : 0;
        }
        
    private:
        void MasterLoop(std::stop_token st); 
        // Helper to run the actual decode.
        void PerformDecode(const std::wstring& path, std::stop_token st);

        ImageEngine* m_parent;
        CImageLoader* m_loader;
        QuantumArenaPool* m_pool; // Shared Pool (Thread-safe usage logic required)

        std::jthread m_thread; 
        
        std::mutex m_resultMutex;
        std::deque<EngineEvent> m_results;
        
        std::atomic<bool> m_isBusy = false;
        std::atomic<bool> m_isCancelling = false;
        std::atomic<int> m_cancelCount = 0;
        
        // --- Synchronization for Single-Slot Logic ---
        std::mutex m_jobMutex;
        std::condition_variable m_jobCv;
        std::wstring m_pendingPath;
        bool m_hasPendingJob = false;
        std::stop_source m_currentJobStopSource; // To cancel the running decode
        
        // Debug
        std::atomic<double> m_lastDecodeTimeMs = 0.0;
        std::wstring m_lastLoaderName;

        mutable std::mutex m_debugMutex; // Protect string access
        
    } m_heavy;

    // Tracking
    std::wstring m_currentNavPath;
    std::chrono::steady_clock::time_point m_lastInputTime;
    
    // [v3.1]
    std::atomic<bool> m_hasEmbeddedThumb = false;
    
    // [Phase 3] Navigation Token for event filtering
    std::atomic<uint64_t> m_currentNavToken = 0;

public:
    bool HasEmbeddedThumb() const { return m_hasEmbeddedThumb.load(); }
};
